{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-api.secretName" . }}
  labels:
    {{- include "stock-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  FINNHUB_API_KEY: {{ .Values.secret.finnhubApiKey | quote }}
{{- end }}
